language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t cdfairchild/docker-react -f dockerfile.dev .

scripts:
  - docker run -e CI=true cdfairchild/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-128936874023"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
